function p = training(p)

% Give feedback during training
p.feedback = 1;

% Initial instruction
text = ['Thank you for your participation in the current study!'...
    '\n\nWe are interested in people''s ability to make quick perceptual decisions.'...
    '\n\nIf at any point you have questions, please stop and ask the experimenter.'...
    '\n\n\n\nPress any key to continue.'];
DrawFormattedText(p.window, text, 300, 'center', 255, p.wrapat);
Screen('Flip',p.window);
WaitSecs(1);
KbWait;

% Initial task instruction
text = ['In this study you will see quickly presented gratings. '...
    'Your job will be to indicate the orientation of the grating, '...
    'either left (like \) or right (like /).' ...
    '\n\nPress any key to continue.'];
DrawFormattedText(p.window, text, 300, 'center', 255, p.wrapat);
Screen('Flip',p.window);
WaitSecs(1);
KbWait;

text = ['After you indicate the orientation of the grating, you will be asked to '...
    'make your choice again. However, for your second response, you will be additionally '...
    'provided with a cue, which  In the other half of the blocks '...
    'the cue will come after the grating.'...
    '\n\nCues will read either:'...
    '\n\n    <  (Left)'...
    '\n\n    >  (Right)'...
    '\n\n    or'...
    '\n\n    |  (Neutral)'...
    '\n\nFor now, you can ignore these cues and only focus on the gratings. We''ll return to the cues later.'...
    '\n\nPress any key now to start two short practice blocks.'];
DrawFormattedText(p.window, text, 300, 'center', 255, p.wrapat);
Screen('Flip',p.window);
WaitSecs(1);
KbWait;

% Give practice run of 4 blocks of increasing difficulty
% one_block(p, number_trials, cue_onset)
p.orientationOffset = 45;
text = ['Practice Block 1']; %offset 45
DrawFormattedText(p.window, text, 'center', 'center', 255);
Screen('Flip',p.window);
WaitSecs(1);
p.practice{1} = one_block(p, 6, 1); %GIVE INSTRUCTIONS BETWEEN BLOCKS
p.orientationOffset = 30;
text = ['Practice Block 2']; %offset 30
DrawFormattedText(p.window, text, 'center', 'center', 255);
Screen('Flip',p.window);
WaitSecs(1);
p.practice{2} = one_block(p, 6, 2);

%Additional Instructions
text = ['Hopefully you are getting comfortable with the task.'...
        '\n\nYou may have noticed that when the cue is presented before the stimulus, a horizontal line (-) appears '...
        'after the stimulus. Similarly, when the cue is presented after the stimulus, the same horizontal line '...
        'appears before the stimulus. You can simply ignore this horizontal line; it is simply there to make both blocks '...
        'as similar as possible.'...
        '\n\nIn addition, make sure to always fix your eyes on the small fixation circle in the middle of the screen '...
        'and don''t move your eyes around.'...
        '\n\nPress any key now to start two more practice blocks.'];
DrawFormattedText(p.window, text, 300, 'center', 255, p.wrapat);
Screen('Flip',p.window);  
KbWait;
p.orientationOffset = 15;
text = ['Practice Block 3']; %offset 15
DrawFormattedText(p.window, text, 'center', 'center', 255);
Screen('Flip',p.window);
WaitSecs(1);
p.practice{3} = one_block(p, 6, 1);
p.orientationOffset = 10;
text = ['Practice Block 4']; %offset 10
DrawFormattedText(p.window, text, 'center', 'center', 255);
Screen('Flip',p.window);
WaitSecs(1);
p.practice{4} = one_block(p, 6, 2);


%Additional Instructions
text = ['You probably noticed that the task became more difficult and you may have made a few errors. This is normal. '...
    'In fact, in the next two practice blocks we will make the task even harder. '...
    '\n\nTo do better on the task, you would need to start using the cues more. A left cue (<) indicates that the stimulus '...
    'has exactly 2/3 chance (66.67%) of being tilted to the left. Similarly, a right cue (>) indicates that the stimulus '...
    'has exactly 2/3 chance (66.67%) of being tilted to the right. Finally, a neutral cue (|) indicates equal probability '...
    'for each stimulus.'...
    '\n\nOne of our main interests in this study is how you use the cues to make better decisions. Please, use them to '...
    'your advantage.'...
    '\n\nPress any key now to start two more practice blocks.'];
DrawFormattedText(p.window, text, 300, 'center', 255, p.wrapat);
Screen('Flip',p.window);
KbWait;
p.orientationOffset = 5;
text = ['Practice Block 5']; %offset 5
DrawFormattedText(p.window, text, 'center', 'center', 255);
Screen('Flip',p.window);
WaitSecs(1);
p.practice{5} = one_block(p, 6, 1);
p.orientationOffset = 3;
text = ['Practice Block 6']; %offset 3
DrawFormattedText(p.window, text, 'center', 'center', 255);
Screen('Flip',p.window);
WaitSecs(1);
p.practice{6} = one_block(p, 6, 2);
WaitSecs(.5);


% Staircase, no feedback given
p.feedback = 0;
text = ['You are almost done with the practice.'...
    '\n\nIn the actual experiment, you won''t receive feedback after every trial. To accustom you to not receiving '...
    'feedback, the next and final practice block will not include feedback after each trial. '...
    '\n\nNote: As an exception, in this block you will only be presented with neutral ( ''|'' ) cues. '...
    'The task will start off quite easy but will quickly become more difficult. The purpose of this block is to '...
    'determine how well you can perform the task without the help of the cues. '...
    '\n\nThis block will be longer than the previous ones in this training.'...
    '\n\nRemember: Always fixate on the small fixation circle, don''t move your eyes around, and do your best!'...
    '\n\nPress any key to continue to the final practice block.'];
DrawFormattedText(p.window, text, 300, 'center', 255, p.wrapat);
Screen('Flip',p.window);
WaitSecs(1);
KbWait;
p.feedback = 0;
p.staircase = one_block_staircase(p, 1000, 1);
p.orientationOffset = p.staircase.orientationOffset;